/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Dark cinematic palette
        background: {
          DEFAULT: '#090A0B',
          hover: '#0F1012',
        },
        surface: {
          DEFAULT: '#101214',
          elevated: '#151719',
        },
        foreground: {
          DEFAULT: '#F1F1ED',
          secondary: '#A6A7A3',
          muted: '#686A68',
        },
        border: {
          DEFAULT: 'rgba(241, 241, 237, 0.10)',
          strong: 'rgba(241, 241, 237, 0.18)',
        },
        accent: {
          DEFAULT: '#C7FF6B',
          muted: 'rgba(199, 255, 107, 0.12)',
          cyan: '#06D6FF',
          purple: '#A78BFA',
          coral: '#FF6B6B',
          gold: '#FBBF24',
          emerald: '#10B981',
          pink: '#F472B6',
          blue: '#3B82F6',
        },
        status: '#B8FF7A',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Geist Mono', 'Monaco', 'Courier New', 'monospace'],
      },
      fontWeight: {
        thin: '100',
        extralight: '200',
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '1.4', letterSpacing: '0.5px', fontWeight: '500' }],
        sm: ['14px', { lineHeight: '1.5', letterSpacing: '0.25px' }],
        base: ['16px', { lineHeight: '1.6' }],
        lg: ['18px', { lineHeight: '1.6', letterSpacing: '-0.2px' }],
        xl: ['20px', { lineHeight: '1.7', letterSpacing: '-0.3px' }],
        '2xl': ['24px', { lineHeight: '1.8', letterSpacing: '-0.4px', fontWeight: '600' }],
        '3xl': ['32px', { lineHeight: '1.8', letterSpacing: '-0.6px', fontWeight: '700' }],
        '4xl': ['48px', { lineHeight: '1.8', letterSpacing: '-1px', fontWeight: '700' }],
        '5xl': ['64px', { lineHeight: '1.8', letterSpacing: '-1.5px', fontWeight: '800' }],
        '6xl': ['80px', { lineHeight: '1.8', letterSpacing: '-2px', fontWeight: '800' }],
      },
      letterSpacing: {
        tighter: '-0.05em',
        tight: '-0.025em',
        normal: '0em',
        wide: '0.025em',
        wider: '0.05em',
        widest: '0.1em',
        ultra: '0.15em',
      },
      lineHeight: {
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
      },
      spacing: {
        '4xs': '2px',
        '3xs': '4px',
        '2xs': '8px',
        xs: '12px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        '2xl': '64px',
        '3xl': '80px',
        '4xl': '96px',
        '5xl': '120px',
      },
      boxShadow: {
        none: 'none',
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        sm: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        base: '0 4px 12px 0 rgba(0, 0, 0, 0.15)',
        md: '0 8px 16px 0 rgba(0, 0, 0, 0.2)',
        lg: '0 12px 24px 0 rgba(0, 0, 0, 0.25)',
        xl: '0 16px 32px 0 rgba(0, 0, 0, 0.3)',
        '2xl': '0 20px 40px 0 rgba(0, 0, 0, 0.35)',
        // Premium elevation shadows
        elevation: {
          1: '0 2px 4px 0 rgba(0, 0, 0, 0.1), inset 0 1px 0 0 rgba(255, 255, 255, 0.05)',
          2: '0 4px 8px 0 rgba(0, 0, 0, 0.15), 0 0 1px 0 rgba(0, 0, 0, 0.1)',
          3: '0 8px 16px 0 rgba(0, 0, 0, 0.2), 0 0 1px 0 rgba(0, 0, 0, 0.15)',
          4: '0 12px 24px 0 rgba(0, 0, 0, 0.25), 0 0 2px 0 rgba(0, 0, 0, 0.2)',
          5: '0 16px 32px 0 rgba(0, 0, 0, 0.3), 0 0 2px 0 rgba(0, 0, 0, 0.25)',
        },
        // Accent glow shadows
        'glow-cyan': '0 0 20px rgba(6, 214, 255, 0.3), 0 0 40px rgba(6, 214, 255, 0.1)',
        'glow-cyan-lg': '0 0 30px rgba(6, 214, 255, 0.4), 0 0 60px rgba(6, 214, 255, 0.2)',
        'glow-purple': '0 0 20px rgba(167, 139, 250, 0.3), 0 0 40px rgba(167, 139, 250, 0.1)',
        'glow-gold': '0 0 20px rgba(251, 191, 36, 0.3), 0 0 40px rgba(251, 191, 36, 0.1)',
        'glow-emerald': '0 0 20px rgba(16, 185, 129, 0.3), 0 0 40px rgba(16, 185, 129, 0.1)',
        'glow-coral': '0 0 20px rgba(255, 107, 107, 0.3), 0 0 40px rgba(255, 107, 107, 0.1)',
      },
      screens: {
        xs: '360px',
        sm: '375px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1440px',
      },
      transitionDuration: {
        fast: '150ms',
        base: '250ms',
        slow: '300ms',
        slower: '500ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        premium: 'cubic-bezier(0.35, 0, 0.2, 1)',
        'ease-smooth': 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
        'ease-premium': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
      },
      borderRadius: {
        none: '0',
        xs: '4px',
        sm: '6px',
        base: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        '3xl': '32px',
        full: '9999px',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        rotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(6, 214, 255, 0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(6, 214, 255, 0.6)' },
        },
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        floatUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        cardLift: {
          'from': { transform: 'translateY(0)', boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)' },
          'to': { transform: 'translateY(-8px)', boxShadow: '0 12px 24px rgba(6, 214, 255, 0.15)' },
        },
        borderBottomExpand: {
          'from': { width: '0' },
          'to': { width: '100%' },
        },
        staggeredReveal: {
          '0%': { opacity: '0', transform: 'translateY(20px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        ripple: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(4)', opacity: '0' },
        },
        bounceIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1' },
          '70%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
        bounceOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '30%': { transform: 'scale(1.05)' },
          '100%': { opacity: '0', transform: 'scale(0.3)' },
        },
        pulseGrow: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        rotateIn: {
          '0%': { opacity: '0', transform: 'rotate(-10deg) scale(0.95)' },
          '100%': { opacity: '1', transform: 'rotate(0) scale(1)' },
        },
        rotateOut: {
          '0%': { opacity: '1', transform: 'rotate(0) scale(1)' },
          '100%': { opacity: '0', transform: 'rotate(10deg) scale(0.95)' },
        },
        zoomIn: {
          '0%': { opacity: '0', transform: 'scale(0.7)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        zoomOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.7)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-50px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRightAdv: {
          '0%': { opacity: '0', transform: 'translateX(50px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInTop: {
          '0%': { opacity: '0', transform: 'translateY(-50px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInBottom: {
          '0%': { opacity: '0', transform: 'translateY(50px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-5px)' },
          '75%': { transform: 'translateX(5px)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-2px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(2px)' },
        },
        wave: {
          '0%': { transform: 'rotate(0deg)' },
          '10%': { transform: 'rotate(14deg)' },
          '20%': { transform: 'rotate(-8deg)' },
          '30%': { transform: 'rotate(14deg)' },
          '40%': { transform: 'rotate(-4deg)' },
          '50%': { transform: 'rotate(10deg)' },
          '60%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        flip: {
          '0%': { transform: 'perspective(400px) rotateY(0)' },
          '100%': { transform: 'perspective(400px) rotateY(360deg)' },
        },
        heartbeat: {
          '0%, 100%': { transform: 'scale(1)' },
          '14%': { transform: 'scale(1.3)' },
          '28%': { transform: 'scale(1)' },
          '42%': { transform: 'scale(1.3)' },
          '70%': { transform: 'scale(1)' },
        },
        swing: {
          '20%': { transform: 'rotate(15deg)' },
          '40%': { transform: 'rotate(-10deg)' },
          '60%': { transform: 'rotate(5deg)' },
          '80%': { transform: 'rotate(-5deg)' },
          '100%': { transform: 'rotate(0deg)' },
        },
        blinkAdv: {
          '0%, 49%, 100%': { opacity: '1' },
          '50%, 99%': { opacity: '0.3' },
        },
        jello: {
          '0%, 11.1%, 100%': { transform: 'none' },
          '22.2%': { transform: 'skewX(-12.5deg) skewY(-12.5deg)' },
          '33.3%': { transform: 'skewX(6.25deg) skewY(6.25deg)' },
          '44.4%': { transform: 'skewX(-3.125deg) skewY(-3.125deg)' },
          '55.5%': { transform: 'skewX(1.5625deg) skewY(1.5625deg)' },
          '66.6%': { transform: 'skewX(-0.78125deg) skewY(-0.78125deg)' },
          '77.7%': { transform: 'skewX(0.390625deg) skewY(0.390625deg)' },
          '88.8%': { transform: 'skewX(-0.1953125deg) skewY(-0.1953125deg)' },
        },
        bubble: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'translateY(-30px) scale(1.2)', opacity: '0' },
        },
        fadeRotate: {
          '0%': { opacity: '0', transform: 'rotate(-180deg)' },
          '100%': { opacity: '1', transform: 'rotate(0deg)' },
        },
        slideFadeIn: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        pop: {
          '0%': { transform: 'scale(0)' },
          '50%': { transform: 'scale(1.2)' },
          '100%': { transform: 'scale(1)' },
        },
        slideExpand: {
          '0%': { opacity: '0', maxHeight: '0', transform: 'translateY(-20px)' },
          '100%': { opacity: '1', maxHeight: '500px', transform: 'translateY(0)' },
        },
        gradientMove: {
          '0%': { backgroundPosition: '0% center' },
          '50%': { backgroundPosition: '100% center' },
          '100%': { backgroundPosition: '0% center' },
        },
        neonGlow: {
          '0%, 100%': { textShadow: '0 0 10px rgba(6, 214, 255, 0.5), 0 0 20px rgba(6, 214, 255, 0.3)' },
          '50%': { textShadow: '0 0 20px rgba(6, 214, 255, 0.8), 0 0 40px rgba(6, 214, 255, 0.5), 0 0 60px rgba(6, 214, 255, 0.3)' },
        },
        typing: {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        blink_caret: {
          '0%, 100%': { borderColor: 'transparent' },
          '50%': { borderColor: 'rgba(6, 214, 255, 0.7)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.3s ease-in-out',
        scaleIn: 'scaleIn 0.3s ease-in-out',
        slideUp: 'slideUp 0.3s ease-in-out',
        slideDown: 'slideDown 0.3s ease-in-out',
        rotate: 'rotate 20s linear infinite',
        glowPulse: 'glowPulse 2s ease-in-out infinite',
        gradientShift: 'gradientShift 6s ease infinite',
        shimmer: 'shimmer 2s infinite',
        floatUp: 'floatUp 0.6s ease-out forwards',
        cardLift: 'cardLift 0.3s ease-out forwards',
        borderBottomExpand: 'borderBottomExpand 0.5s ease-out forwards',
        staggeredReveal: 'staggeredReveal 0.6s ease-out forwards',
        ripple: 'ripple 0.6s ease-out',
        bounceIn: 'bounceIn 0.6s ease-out forwards',
        bounceOut: 'bounceOut 0.6s ease-in forwards',
        pulseGrow: 'pulseGrow 2s ease-in-out infinite',
        rotateIn: 'rotateIn 0.6s ease-out forwards',
        rotateOut: 'rotateOut 0.6s ease-in forwards',
        zoomIn: 'zoomIn 0.5s ease-out forwards',
        zoomOut: 'zoomOut 0.5s ease-in forwards',
        slideInLeft: 'slideInLeft 0.6s ease-out forwards',
        slideInRight: 'slideInRightAdv 0.6s ease-out forwards',
        slideInTop: 'slideInTop 0.6s ease-out forwards',
        slideInBottom: 'slideInBottom 0.6s ease-out forwards',
        wiggle: 'wiggle 0.5s ease-in-out infinite',
        shake: 'shake 0.5s ease-in-out infinite',
        wave: 'wave 1s ease-in-out infinite',
        flip: 'flip 0.6s ease-out forwards',
        heartbeat: 'heartbeat 1.3s ease-in-out infinite',
        swing: 'swing 0.5s ease-in-out forwards',
        blinkAdv: 'blinkAdv 1s ease-in-out infinite',
        jello: 'jello 0.9s ease-out forwards',
        bubble: 'bubble 1s ease-out forwards',
        fadeRotate: 'fadeRotate 0.6s ease-out forwards',
        slideFadeIn: 'slideFadeIn 0.5s ease-out forwards',
        pop: 'pop 0.4s cubic-bezier(0.68, -0.55, 0.265, 1.55) forwards',
        slideExpand: 'slideExpand 0.4s ease-out forwards',
        gradientMove: 'gradientMove 8s ease infinite',
        neonGlow: 'neonGlow 2s ease-in-out infinite',
        typing: 'typing 3.5s steps(40, end)',
        blink_caret: 'blink_caret 0.75s step-end infinite',
      },
    },
  },
  plugins: [require('@tailwindcss/container-queries')],
};
